# -*- coding: utf-8 -*-
"""Manalo_RamAndrei_PDC_Assignment2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RtDSnaZbd0z_Yo38bnywdlnxOOsrFlbr
"""

!apt-get install -y mpich
!pip install mpi4py

from mpi4py import MPI

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

if rank == 0:
  for i in range(1, size):
    message = comm.recv(source=i)
    print(f"Received from process {i}: {message}")
else:
  comm.send(f"Hello from process {rank}", dest=0)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile manalo_mpi.py
# from mpi4py import MPI
# 
# comm = MPI.COMM_WORLD
# rank = comm.Get_rank()
# size = comm.Get_size()
# 
# if rank == 0:
#   for i in range(1, size):
#     message = comm.recv(source=i)
#     print(f"Received from process {i}: {message}")
# else:
#   comm.send(f"Hello from process {rank}", dest=0)

!mpirun -np 4 python manalo_mpi.py

!mpirun --allow-run-as-root -np 2 python manalo_mpi.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile manalo_mpi.py
# from mpi4py import MPI
# 
# comm = MPI.COMM_WORLD
# rank = comm.Get_rank()
# size = comm.Get_size()
# 
# if rank == 0:
#     print("Master process started.\n")
#     for i in range(1, size):
#         message = comm.recv(source=i)
#         print(f"Received from process {i}:")
#         print(f"Task: {message['task']}")
#         print(f"Result: {message['result']}\n")
# else:
#     x = rank * 10
#     y = x + 9
#     data_chunk = list(range(x, y + 1))
#     result = sum(data_chunk)
# 
#     message = {
#         "rank": rank,
#         "task": f"Sum of numbers from {x} to {y}",
#         "result": result
#     }
# 
#     comm.send(message, dest=0)
#

!mpiexec --allow-run-as-root -n 4 python manalo_mpi.py

!mpirun --allow-run-as-root --oversubscribe -n 4 python manalo_mpi.py

!python3 -m pip install mpi4py

!mpiexec --allow-run-as-root --oversubscribe -n 4 python3 manalo_mpi.py